version: '3.9'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: udyam
      POSTGRES_PASSWORD: udyam
      POSTGRES_DB: udyam
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: .
    environment:
      NODE_ENV: production
      PORT: 4000
      CORS_ORIGIN: "*"
      DB_DRIVER: postgres
      DATABASE_URL: postgresql://udyam:udyam@db:5432/udyam?schema=public
    ports:
      - "4000:4000"
    depends_on:
      - db
volumes:
  pgdata:


